# Model arguments
model_name_or_path: /data/model/Qwen2.5-Math-7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: knoveleng/open-rs
system_prompt: "A conversation between User and Assistant. The user asks a question, and the Assistant solves it. The assistant first thinks about the reasoning process in the mind and then provides the user with the answer, and put your final answer within \\boxed{{}} . The reasoning process and answer are enclosed within <think> </think> and <answer> </answer> tags, respectively, i.e., <think> reasoning process here </think> <answer> answer here </answer>. Note that respond by English, NOT use other languages."



use_peft: True
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules: # ['q_proj', 'v_proj']
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj


# GRPO trainer config
bf16: true
use_vllm: true
vllm_mode: colocate
vllm_tensor_parallel_size: 1
vllm_gpu_memory_utilization: 0.4  # 1.5B的话可以设置为0.1
do_eval: false
gradient_accumulation_steps: 6
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-Math-7B-ERPER-GRPO-alpha99-newSTD
hub_strategy: every_save
learning_rate: 5.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
max_prompt_length: 512   # 512
max_completion_length: 1024  # 3584
max_steps: 100
num_generations: 6 #6
num_train_epochs: 1
output_dir: Qwen2.5-Math-7B-data-DrGRPO/ERPER-GRPO-alpha99-newSTD
overwrite_output_dir: true
per_device_eval_batch_size: 6 #6
per_device_train_batch_size: 1 #6
push_to_hub: true
report_to:
- wandb
reward_funcs:
- format
- cosine
reward_weights:
- 1.0
- 2.0
save_strategy: "steps"
save_steps: 50
seed: 2025
temperature: 0.7
warmup_ratio: 0.1
SMI_reweighting: False
extractor_name: hidden_state

# 如果reward alpha是1.0就是原始的GRPO算法 ,reward_alpha: 0.1或者0.9
reward_alpha: 0.99

use_per: True  # 是否使用PER


# 需要配置的GRPO参数，也即修改的默认配置
beta: 0.04
epsilon: 0.2
epsilon_high: 0.28

loss_type: "dr_grpo"   # "grpo" or "dr_grpo" or "dnpo"
scale_rewards: False